version: '3'
services:
#  mongodb:
#    container_name: mongo-db
#    image: mongo:3
#  elasticsearch:
#    container_name: elastic
#    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.1
#    environment:
#      - http.host=0.0.0.0
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#      - transport.host=localhost
#      - network.host=0.0.0.0
  couchdb:
    container_name: couchdb
    image: couchdb:3.1.0
    environment:
      - COUCHDB_USER=admin 
      - COUCHDB_PASSWORD=1password1
    ports:
      - 4369:4369
      - 5984:5984
      - 9100:9100
